"""create initial schema

Revision ID: f8d739439ed0
Revises:
Create Date: 2026-07-03 12:39:54.504803
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f8d739439ed0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_items',
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('canonical_title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('superseded_by_item_id', sa.BigInteger(), nullable=True),
    sa.Column('merged_into_item_id', sa.BigInteger(), nullable=True),
    sa.Column('data_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('geographic_scope', sa.String(length=40), nullable=False),
    sa.Column('uae_relevance_status', sa.String(length=40), nullable=False),
    sa.Column('uae_relevance_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('uae_relevance_reason', sa.String(length=1000), nullable=True),
    sa.Column('uae_relevance_method', sa.String(length=40), nullable=False),
    sa.Column('analyst_review_status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("geographic_scope IN ('global', 'regional', 'uae', 'unknown')", name='ck_intelligence_items_geographic_scope_allowed'),
    sa.CheckConstraint("item_type IN ('vulnerability', 'security_advisory', 'cyber_news', 'threat_report', 'uae_official_alert', 'other_defensive_intel')", name='ck_intelligence_items_item_type_allowed'),
    sa.CheckConstraint("status <> 'merged' OR merged_into_item_id IS NOT NULL", name='ck_intelligence_items_merged_requires_target'),
    sa.CheckConstraint("status <> 'superseded' OR superseded_by_item_id IS NOT NULL", name='ck_intelligence_items_superseded_requires_target'),
    sa.CheckConstraint("status IN ('active', 'superseded', 'merged', 'archived')", name='ck_intelligence_items_status_allowed'),
    sa.CheckConstraint("uae_relevance_method IN ('automatic', 'manual', 'source_declared', 'unassigned')", name='ck_intelligence_items_uae_relevance_method_allowed'),
    sa.CheckConstraint("uae_relevance_status IN ('confirmed', 'probable', 'possible', 'not_relevant', 'unknown')", name='ck_intelligence_items_uae_relevance_status_allowed'),
    sa.CheckConstraint('data_confidence IS NULL OR (data_confidence >= 0 AND data_confidence <= 1)', name='ck_intelligence_items_data_confidence_range'),
    sa.CheckConstraint('merged_into_item_id IS NULL OR merged_into_item_id <> id', name='ck_intelligence_items_merged_into_not_self'),
    sa.CheckConstraint('superseded_by_item_id IS NULL OR merged_into_item_id IS NULL', name='ck_intelligence_items_single_lifecycle_pointer'),
    sa.CheckConstraint('superseded_by_item_id IS NULL OR superseded_by_item_id <> id', name='ck_intelligence_items_superseded_by_not_self'),
    sa.CheckConstraint('uae_relevance_confidence IS NULL OR (uae_relevance_confidence >= 0 AND uae_relevance_confidence <= 1)', name='ck_intelligence_items_uae_relevance_confidence_range'),
    sa.ForeignKeyConstraint(['merged_into_item_id'], ['intelligence_items.id'], name=op.f('fk_intelligence_items_merged_into_item_id_intelligence_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_item_id'], ['intelligence_items.id'], name=op.f('fk_intelligence_items_superseded_by_item_id_intelligence_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_items')),
    sa.UniqueConstraint('public_id', name=op.f('uq_intelligence_items_public_id'))
    )
    op.create_index('ix_intel_items_uae_rel_status_published_desc', 'intelligence_items', ['uae_relevance_status', sa.literal_column('source_published_at DESC')], unique=False)
    op.create_index('ix_intelligence_items_item_type_source_published_at_desc', 'intelligence_items', ['item_type', sa.literal_column('source_published_at DESC')], unique=False)
    op.create_index('ix_intelligence_items_status_source_published_at_desc', 'intelligence_items', ['status', sa.literal_column('source_published_at DESC')], unique=False)
    op.create_table('intelligence_sources',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_notes', sa.String(length=500), nullable=True),
    sa.Column('last_successful_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkpoint_value', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('api', 'rss', 'csv', 'json')", name='ck_intelligence_sources_source_type_allowed'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_intelligence_sources_name')),
    sa.UniqueConstraint('public_id', name=op.f('uq_intelligence_sources_public_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_intelligence_sources_slug'))
    )
    op.create_table('tags',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('tag_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint("tag_type IN ('general', 'vendor', 'product', 'sector', 'region', 'technique', 'theme')", name='ck_tags_tag_type_allowed'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('slug', name=op.f('uq_tags_slug'))
    )
    op.create_table('ingestion_runs',
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('checkpoint_before', sa.String(length=500), nullable=True),
    sa.Column('checkpoint_after', sa.String(length=500), nullable=True),
    sa.Column('safe_summary', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'partial', 'failed', 'canceled')", name='ck_ingestion_runs_status_allowed'),
    sa.CheckConstraint("trigger_type IN ('scheduled', 'manual', 'retry')", name='ck_ingestion_runs_trigger_type_allowed'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name='ck_ingestion_runs_completed_at_order'),
    sa.CheckConstraint('records_fetched >= 0 AND records_created >= 0 AND records_updated >= 0 AND records_unchanged >= 0 AND records_skipped >= 0 AND records_failed >= 0 AND error_count >= 0', name='ck_ingestion_runs_counters_non_negative'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], name=op.f('fk_ingestion_runs_source_id_intelligence_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs')),
    sa.UniqueConstraint('public_id', name=op.f('uq_ingestion_runs_public_id'))
    )
    op.create_index('ix_ingestion_runs_source_id_started_at_desc', 'ingestion_runs', ['source_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_ingestion_runs_status_started_at_desc', 'ingestion_runs', ['status', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('intelligence_item_tags',
    sa.Column('intelligence_item_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("assigned_by IN ('system', 'analyst', 'source')", name='ck_intelligence_item_tags_assigned_by_allowed'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_intelligence_item_tags_confidence_range'),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['intelligence_items.id'], name=op.f('fk_intelligence_item_tags_intelligence_item_id_intelligence_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_intelligence_item_tags_tag_id_tags'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('intelligence_item_id', 'tag_id', name=op.f('pk_intelligence_item_tags'))
    )
    op.create_index('ix_intelligence_item_tags_tag_id_item_id', 'intelligence_item_tags', ['tag_id', 'intelligence_item_id'], unique=False)
    op.create_table('source_records',
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('intelligence_item_id', sa.BigInteger(), nullable=True),
    sa.Column('source_external_id', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_primary_reference', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=40), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_error_summary', sa.String(length=1000), nullable=True),
    sa.Column('upstream_status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("processing_status IN ('pending', 'processed', 'skipped', 'failed')", name='ck_source_records_processing_status_allowed'),
    sa.CheckConstraint("upstream_status IN ('present', 'missing', 'unavailable')", name='ck_source_records_upstream_status_allowed'),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['intelligence_items.id'], name=op.f('fk_source_records_intelligence_item_id_intelligence_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], name=op.f('fk_source_records_source_id_intelligence_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records'))
    )
    op.create_index('uq_source_records_external_id', 'source_records', ['source_id', 'source_external_id'], unique=True, postgresql_where=sa.text('source_external_id IS NOT NULL'))
    op.create_index('uq_source_records_primary_ref_per_item', 'source_records', ['intelligence_item_id'], unique=True, postgresql_where=sa.text('is_primary_reference IS TRUE AND intelligence_item_id IS NOT NULL'))
    op.create_index('uq_source_records_url_hash', 'source_records', ['source_id', 'canonical_url_hash'], unique=True, postgresql_where=sa.text('canonical_url_hash IS NOT NULL'))
    op.create_table('vulnerabilities',
    sa.Column('intelligence_item_id', sa.BigInteger(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cvss_vector', sa.String(length=300), nullable=True),
    sa.Column('cvss_version', sa.String(length=10), nullable=True),
    sa.Column('epss_score', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('epss_percentile', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('kev_status', sa.String(length=20), nullable=False),
    sa.Column('kev_last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kev_date_added', sa.Date(), nullable=True),
    sa.Column('kev_due_date', sa.Date(), nullable=True),
    sa.Column('kev_required_action', sa.Text(), nullable=True),
    sa.Column('known_ransomware_campaign_use', sa.Boolean(), nullable=True),
    sa.Column('affected_summary', sa.Text(), nullable=True),
    sa.Column('affected_products_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kev_status IN ('unknown', 'not_listed', 'listed')", name='ck_vulnerabilities_kev_status_allowed'),
    sa.CheckConstraint("severity IS NULL OR severity IN ('unknown', 'none', 'low', 'medium', 'high', 'critical')", name='ck_vulnerabilities_severity_allowed'),
    sa.CheckConstraint('cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)', name='ck_vulnerabilities_cvss_score_range'),
    sa.CheckConstraint('epss_percentile IS NULL OR (epss_percentile >= 0 AND epss_percentile <= 1)', name='ck_vulnerabilities_epss_percentile_range'),
    sa.CheckConstraint('epss_score IS NULL OR (epss_score >= 0 AND epss_score <= 1)', name='ck_vulnerabilities_epss_score_range'),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['intelligence_items.id'], name=op.f('fk_vulnerabilities_intelligence_item_id_intelligence_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities')),
    sa.UniqueConstraint('intelligence_item_id', name=op.f('uq_vulnerabilities_intelligence_item_id'))
    )
    op.create_index('ix_vulnerabilities_kev_status', 'vulnerabilities', ['kev_status'], unique=False)
    op.create_index('ix_vulnerabilities_severity', 'vulnerabilities', ['severity'], unique=False)
    op.create_table('ingestion_run_records',
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_record_id', sa.BigInteger(), nullable=True),
    sa.Column('intelligence_item_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('safe_detail', sa.String(length=1000), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint("action IN ('created', 'updated', 'unchanged', 'skipped', 'failed')", name='ck_ingestion_run_records_action_allowed'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_ingestion_run_records_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['intelligence_items.id'], name=op.f('fk_ingestion_run_records_intelligence_item_id_intelligence_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_ingestion_run_records_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_run_records'))
    )
    op.create_index('ix_ingestion_run_records_run_id_action', 'ingestion_run_records', ['ingestion_run_id', 'action'], unique=False)
    op.create_index('uq_ingestion_run_records_run_source_record', 'ingestion_run_records', ['ingestion_run_id', 'source_record_id'], unique=True, postgresql_where=sa.text('source_record_id IS NOT NULL'))
    op.create_table('intelligence_item_identifiers',
    sa.Column('intelligence_item_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_record_id', sa.BigInteger(), nullable=True),
    sa.Column('namespace', sa.String(length=40), nullable=False),
    sa.Column('identifier_value', sa.String(length=300), nullable=False),
    sa.Column('normalized_value', sa.String(length=300), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['intelligence_items.id'], name=op.f('fk_intelligence_item_identifiers_intelligence_item_id_intelligence_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], name=op.f('fk_intelligence_item_identifiers_source_id_intelligence_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_intelligence_item_identifiers_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_item_identifiers'))
    )
    op.create_index('uq_item_identifiers_global_lookup', 'intelligence_item_identifiers', ['namespace', 'normalized_value'], unique=True, postgresql_where=sa.text('source_id IS NULL'))
    op.create_index('uq_item_identifiers_primary_per_item', 'intelligence_item_identifiers', ['intelligence_item_id'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))
    op.create_index('uq_item_identifiers_source_lookup', 'intelligence_item_identifiers', ['source_id', 'namespace', 'normalized_value'], unique=True, postgresql_where=sa.text('source_id IS NOT NULL'))
    op.create_table('ingestion_errors',
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_record_id', sa.BigInteger(), nullable=True),
    sa.Column('source_record_id', sa.BigInteger(), nullable=True),
    sa.Column('error_type', sa.String(length=80), nullable=False),
    sa.Column('safe_message', sa.String(length=1000), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint('retry_count >= 0', name='ck_ingestion_errors_retry_count_non_negative'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_ingestion_errors_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_record_id'], ['ingestion_run_records.id'], name=op.f('fk_ingestion_errors_ingestion_run_record_id_ingestion_run_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_ingestion_errors_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_errors'))
    )
    op.create_index('ix_ingestion_errors_run_id_occurred_at_desc', 'ingestion_errors', ['ingestion_run_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_errors_run_id_occurred_at_desc', table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_index('uq_item_identifiers_source_lookup', table_name='intelligence_item_identifiers', postgresql_where=sa.text('source_id IS NOT NULL'))
    op.drop_index('uq_item_identifiers_primary_per_item', table_name='intelligence_item_identifiers', postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_index('uq_item_identifiers_global_lookup', table_name='intelligence_item_identifiers', postgresql_where=sa.text('source_id IS NULL'))
    op.drop_table('intelligence_item_identifiers')
    op.drop_index('uq_ingestion_run_records_run_source_record', table_name='ingestion_run_records', postgresql_where=sa.text('source_record_id IS NOT NULL'))
    op.drop_index('ix_ingestion_run_records_run_id_action', table_name='ingestion_run_records')
    op.drop_table('ingestion_run_records')
    op.drop_index('ix_vulnerabilities_severity', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_kev_status', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index('uq_source_records_url_hash', table_name='source_records', postgresql_where=sa.text('canonical_url_hash IS NOT NULL'))
    op.drop_index('uq_source_records_primary_ref_per_item', table_name='source_records', postgresql_where=sa.text('is_primary_reference IS TRUE AND intelligence_item_id IS NOT NULL'))
    op.drop_index('uq_source_records_external_id', table_name='source_records', postgresql_where=sa.text('source_external_id IS NOT NULL'))
    op.drop_table('source_records')
    op.drop_index('ix_intelligence_item_tags_tag_id_item_id', table_name='intelligence_item_tags')
    op.drop_table('intelligence_item_tags')
    op.drop_index('ix_ingestion_runs_status_started_at_desc', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_source_id_started_at_desc', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('tags')
    op.drop_table('intelligence_sources')
    op.drop_index('ix_intelligence_items_status_source_published_at_desc', table_name='intelligence_items')
    op.drop_index('ix_intelligence_items_item_type_source_published_at_desc', table_name='intelligence_items')
    op.drop_index('ix_intel_items_uae_rel_status_published_desc', table_name='intelligence_items')
    op.drop_table('intelligence_items')
    # ### end Alembic commands ###
